language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t doggers/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true doggers/docker-react npm run test